name: players_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  http: ^0.13.5
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/